FROM python:3.6.4-alpine3.7

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk update && apk add build-base

COPY gunicorn.conf /
COPY main.py /
COPY requirements.sanic /

RUN pip3 install --no-cache-dir -r requirements.sanic

EXPOSE 8000

CMD [ "gunicorn", "-c", "gunicorn.conf", "main:app" ]

