FROM python:3.6.4-alpine3.7

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk update && apk add build-base

COPY main.py /

RUN pip3 install sanic

EXPOSE 8000

CMD [ "python3", "main.py" ]

