FROM python:3.6.4-alpine3.7

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk update && apk add build-base

COPY gunicorn.conf /
COPY things.py /

#COPY requirements.falcon /
#RUN pip3 install --no-cache-dir -r requirements.falcon

RUN pip3 install cython
RUN pip3 install --no-binary :all: falcon
RUN pip3 install requests
RUN pip3 install gunicorn
RUN pip3 install meinheld

EXPOSE 8000

CMD [ "gunicorn", "--config", "gunicorn.conf", "things:app" ]

